// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Talkero.Data;

#nullable disable

namespace Talkero.Migrations
{
    [DbContext(typeof(TalkeroData))]
    [Migration("20220630001350_minizmeny")]
    partial class minizmeny
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Talkero.Models.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Banner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuvodZablokovani")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Heslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JeAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Overen")
                        .HasColumnType("bit");

                    b.Property<string>("Profilovka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SouhlasiSPodminkami")
                        .HasColumnType("bit");

                    b.Property<bool>("Zablokovan")
                        .HasColumnType("bit");

                    b.Property<bool>("ZadaOOdblokovani")
                        .HasColumnType("bit");

                    b.Property<bool>("ZasilatNovinky")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Uzivatele");
                });

            modelBuilder.Entity("Talkero.Models.Zprava", b =>
                {
                    b.Property<int>("ZpravaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZpravaId"), 1L, 1);

                    b.Property<DateTime>("DatumOdeslani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Obrazek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObsahZpravy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZpravaId");

                    b.ToTable("Zpravy");
                });
#pragma warning restore 612, 618
        }
    }
}
